# Confirmed hypotheses
PREFIX ls: <http://linkedscience.org/lsc/ns#>
PREFIX schema: <http://schema.org/>

SELECT ?test ?name WHERE {
  ?topic ls:confirms ?test.
  ?test schema:name ?nameRaw.

  # Remove HTML tags
  BIND(REPLACE(?nameRaw, "<[^>]*>", "", "i") AS ?name)
}