PREFIX ex: <http://example.org/train#>
SELECT ?headSign ?routeLabel ?departureTime
WHERE {
    ex:train4815 t:departureTime ?departureTime.
    ex:train4815 t:headSign      ?headSign.
    ex:train4815 t:routeLabel    ?routeLabel.
    FILTER (?departureTime > "2015-12-08T10:20:00"^^xsd:dateTime).
    FILTER (?departureTime < "2015-12-08T11:20:00"^^xsd:dateTime).
}
